---
# These tasks run on all nodes in the cluster to set common and baseline configuration for kubernetes

- name: 'configure-nodes | ensure sysctl parameters are configured and loaded'
  ansible.builtin.template:
    src: 'kernel-sysctl.conf.j2'
    dest: '/etc/sysctl.d/99-kubeflare-sysctl.conf'
    mode: 0644
  notify: systemd-sysctl configuration changed

- name: 'configure-nodes | ensure modules are configured at node startup'
  ansible.builtin.template:
    src: 'kernel-modules.conf.j2'
    dest: '/etc/modules-load.d/kubeflare-modules.conf'
    mode: 0644

- name: 'configure-nodes | ensure kernel modules are loaded'
  community.general.modprobe:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ kubeflare_kernel.modules }}'
