---

- name: 'pre-flight | check if the installed version of ansible ({{ ansible_version.string }}) is compatible'
  ansible.builtin.assert:
    that:
    - ansible_version.string is version_compare(kubeflare_ansible_min_version, '>=')
    fail_msg: >-
      The version of Ansible installed, {{ ansible_version.string }} is not compatible with this role. The
      minimum supported version is {{ kubeflare_ansible_min_version }}.
    success_msg: 'Ansible {{ ansible_version.string }} is compatible.'
  become: false
  delegate_to: localhost
  run_once: true

- name: 'pre-flight | check if kubeflare_state is valid'
  ansible.builtin.assert:
    that:
    - kubeflare_state in kubeflare_states
    fail_msg: 'kubeflare_state is not valid.'
    success_msg: 'kubeflare_state is valid.'
  run_once: true
  when: kubeflare_state is defined

- name: 'pre-flight | check if configuration valid for a standalone control plane'
  ansible.builtin.assert:
    that:
    - kubeflare_controlplane_list|length == 1
    success_msg: 'Control Plane configuration is valid.'
    fail_msg: >-
      Control Plane configuration is invalid.
  run_once: true
  when:
  - kubeflare_controlplane_list|length == 1

- name: 'pre-flight | check if configuration is valid for an HA control plane'
  ansible.builtin.assert:
    that:
    - kubeflare_controlplane_list|length >= 3
    - (kubeflare_controlplane_list|length % 2) == 1
    success_msg: 'Control Plane HA configuration is valid.'
    fail_msg: >-
      Control Plane HA configuration is invalid. etcd requires a minimum of 3 replicas and
      the number of member nodes should be odd.
  run_once: true
  when:
  - kubeflare_controlplane_list|length > 1

- name: 'pre-flight | check if kubeflare configuration is valid'
  ansible.builtin.assert:
    that:
    - cri_plugin in kubeflare_supported_cri_plugins
    fail_msg: 'Kubeflare configuration is invalid, please verify.'
    success_msg: 'Kubeflare configuration is valid.'
  run_once: true
