---
- hosts: masters
  become: true

  vars_files:
    - ../vars.yml

  roles:
    - keepalived
    - haproxy
    - { role: initial-master, when: "groups['masters'][0] == inventory_hostname" }
    - { role: cni, when: "groups['masters'][0] == inventory_hostname" }
    - { role: masters, when: "groups['masters'][0] != inventory_hostname" }