# Instructions: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
---
- name: Copy containerd config file
  copy:
    src: '{{ item }}'
    dest: '/etc/modules-load.d/containerd.conf'
    owner: root
    group: root
    mode: '0644'
  with_items:
    - containerd.conf

- name: Load overlay
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename}} stable
    state: present

- name: Install containerd package
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
      - containerd.io

- name: Create containerd config directory
  become: true
  file:
    path: /etc/containerd/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure containerd
  shell: containerd config default > /etc/containerd/config.toml

- name: Restart containered
  systemd:
    name: containerd
    state: restarted
