---
ansible_user: pi

log2ram_version: v1.4
log2ram_size: 128M

# Configure Kubernetes binary versions
kubernetes_version: 1.9.6
kubelet_version: 1.9.6-0
kubeadm_version: 1.10.1

# Cloudflare options for exposing Kubernetes services via HTTPS/SSH
cloudflared_ingress_dns: master.raspbernetes.com
cloudflared_ssh_port: 22

# Virtual IP and port used by Keepalived
load_balancer_dns: 192.168.1.201
load_balancer_port: 6443

# Configure Kubernetes container network interface (CNI)
# Options: "weave" or "flannel"
# Default: "weave"
cni: weave

# Configure Kubernetes container runtime (CRI)
# Options: "containerd" or "docker"
# Default: "docker"
cri: docker

# Network interface
# Options: "eth0" or "wlan0"
# Default: "eth0"
network_interface: eth0
